application: stop-social
version: 1
runtime: python27
api_version: 1
threadsafe: True

builtins:
- remote_api: on

inbound_services:
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest